$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  genome:
    type: string
    enum: ["hg38", "hg19", "mm10", "mm9", "dm3", "dm6"]
    description: Genome assembly to use
  
  ensembl_genome_build:
    type: integer
    description: Ensembl genome build version

  umi_tools:
    type: object
    properties:
      pattern:
        type: string
        description: UMI pattern
    required:
      - pattern
  
  cutadapt:
    type: object
    properties:
      adapters:
        type: string
        description: Adapter sequences
      extra:
        type: string
        description: Additional options for cutadapt
    required:
      - adapters
      - extra

  bigwig:
    type: object
    properties:
      binSize:
        type: integer
        description: Bin size for bigWig files
      normalizeUsing:
        type: string
        enum: ["RPKM", "CPM", "BPM", "RPGC", "None"]
        description: Normalization method
      extendReads:
        type: string
        description: Extend reads by this amount
    required:
      - binSize
      - normalizeUsing
      - extendReads

  macs2:
    type: object
    properties:
      run:
        type: boolean
        description: Run MACS2
      qvalue:
        type: number
        maximum: 1
        minimum: 0
        description: q-value threshold
      regions:
        type: string
        enum: ["broad", "narrow"]
        description: Type of regions to call
      broad_cutoff:
        type: number
        maximum: 1
        minimum: 0
        description: Broad cutoff
      extra:
        type: string
        description: Additional options for MACS2
    required:
      - run
      - qvalue
      - regions
      - broad_cutoff
      - extra

  consensus_peaks:
    type: object
    properties:
      max_size:
        type: integer
        description: Maximum size of peaks to be extended
      extend_by:
        type: integer
        description: Number of bp to extend peaks on either side
      keep:
        type: integer
        description: Minimum number peaks that must overlap to keep
    required:
      - max_size
      - extend_by
      - keep